run:
  timeout: 5m
  tests: true

linters:
  enable:
    - govet
    - errcheck
    - staticcheck
    - unused
    - gosimple
    - ineffassign
    - misspell

linters-settings:
  errcheck:
    check-type-assertions: true
  govet:
    enable-all: true
    disable:
      - fieldalignment
      - shadow

issues:
  exclude-dirs:
    - vendor
  exclude-files:
    - ".*\\.pb\\.go$"
  exclude-rules:
    - path: _test\.go  
      linters:
        - unused